// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    district_coverage: {
        name: "district_coverage";
        parameters: {
          /** STRING - use sql.string() */
          state: SQLStringMarker;
          /** STRING - use sql.string() */
          capability: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          district: string;
          /** @sqlType BIGINT */
          n_facilities: number;
          /** @sqlType DOUBLE */
          trust_weighted: number;
          /** @sqlType DOUBLE */
          avg_trust: number;
          /** @sqlType BIGINT */
          catalog_records: number;
          /** @sqlType DOUBLE */
          catalog_trust_weighted: number;
          /** @sqlType DOUBLE */
          avg_catalog_trust: number;
          /** @sqlType BIGINT */
          n_without_named_staff: number;
          /** @sqlType BIGINT */
          n_established_before_2000: number;
          /** @sqlType BIGINT */
          n_stale_web_evidence: number;
          /** @sqlType BIGINT */
          n_with_doctor_count: number;
          /** @sqlType DOUBLE */
          reported_doctors: number;
          /** @sqlType BIGINT */
          n_with_capacity: number;
          /** @sqlType DOUBLE */
          total_reported_capacity: number;
          /** @sqlType BIGINT */
          n_accepts_volunteers: number;
          /** @sqlType BIGINT */
          n_spirometry: number;
          /** @sqlType BIGINT */
          n_oxygen: number;
          /** @sqlType BIGINT */
          n_inhaler_nebulizer: number;
          /** @sqlType BIGINT */
          n_pulmonary_rehab: number;
          /** @sqlType BIGINT */
          n_critical_care: number;
          /** @sqlType BIGINT */
          n_cities_with_supply: number;
          /** @sqlType DECIMAL(26,1) */
          largest_city_share_pct: number;
          /** @sqlType DOUBLE */
          clean_fuel_pct: number;
          /** @sqlType DOUBLE */
          women_tobacco_pct: number;
          /** @sqlType DOUBLE */
          men_tobacco_pct: number;
          /** @sqlType DOUBLE */
          adult_tobacco_pct: number;
          /** @sqlType DOUBLE */
          child_ari_pct: number;
          /** @sqlType DOUBLE */
          insurance_pct: number;
          /** @sqlType DOUBLE */
          estimated_population: number;
          /** @sqlType DOUBLE */
          copd_risk_score: number;
          /** @sqlType DOUBLE */
          gap_score: number;
          /** @sqlType STRING */
          data_confidence: string;
        }>;
      };
    facility_list: {
        name: "facility_list";
        parameters: {
          /** STRING - use sql.string() */
          state: SQLStringMarker;
          /** STRING - use sql.string() */
          district: SQLStringMarker;
          /** STRING - use sql.string() */
          capability: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          facility_id: string;
          /** @sqlType STRING */
          name: string;
          /** @sqlType STRING */
          city: string;
          /** @sqlType STRING */
          district: string;
          /** @sqlType STRING */
          pin: string;
          /** @sqlType DOUBLE */
          latitude: number;
          /** @sqlType DOUBLE */
          longitude: number;
          /** @sqlType DOUBLE */
          trust_score: number;
          /** @sqlType BOOLEAN */
          has_logo: boolean;
          /** @sqlType BOOLEAN */
          has_staff: boolean;
          /** @sqlType INT */
          social_count: number;
          /** @sqlType BOOLEAN */
          has_website: boolean;
          /** @sqlType BOOLEAN */
          recently_updated: boolean;
          /** @sqlType STRING */
          specialties: string;
          /** @sqlType STRING */
          evidence: string;
          /** @sqlType BOOLEAN */
          has_pulmonology: boolean;
          /** @sqlType BOOLEAN */
          has_spirometry: boolean;
          /** @sqlType BOOLEAN */
          has_oxygen: boolean;
          /** @sqlType BOOLEAN */
          has_inhaler_nebulizer: boolean;
          /** @sqlType BOOLEAN */
          has_pulmonary_rehab: boolean;
          /** @sqlType BOOLEAN */
          has_critical_care: boolean;
        }>;
      };
    national_kpis: {
        name: "national_kpis";
        parameters: {
          /** STRING - use sql.string() */
          capability: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType BIGINT */
          n_facilities: number;
          /** @sqlType BIGINT */
          n_states: number;
          /** @sqlType BIGINT */
          n_districts: number;
          /** @sqlType DOUBLE */
          avg_trust: number;
          /** @sqlType DOUBLE */
          trust_weighted: number;
          /** @sqlType BIGINT */
          geocoded: number;
          /** @sqlType DOUBLE */
          avg_copd_risk: number;
        }>;
      };
    partner_candidates: {
        name: "partner_candidates";
        parameters: {
          /** STRING - use sql.string() */
          state: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          facility_id: string;
          /** @sqlType STRING */
          name: string;
          /** @sqlType STRING */
          district: string;
          /** @sqlType STRING */
          organization_type: string;
          /** @sqlType STRING */
          phone: string;
          /** @sqlType STRING */
          email: string;
          /** @sqlType STRING */
          website: string;
          /** @sqlType STRING */
          source_urls: string;
          /** @sqlType BOOLEAN */
          has_pulmonology: boolean;
          /** @sqlType BOOLEAN */
          has_spirometry: boolean;
          /** @sqlType BOOLEAN */
          has_oxygen: boolean;
          /** @sqlType BOOLEAN */
          has_inhaler_nebulizer: boolean;
          /** @sqlType BOOLEAN */
          has_pulmonary_rehab: boolean;
          /** @sqlType BOOLEAN */
          has_critical_care: boolean;
        }>;
      };
    specialty_options: {
        name: "specialty_options";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          capability: string;
          /** @sqlType BIGINT */
          facility_mentions: number;
        }>;
      };
    state_coverage: {
        name: "state_coverage";
        parameters: {
          /** STRING - use sql.string() */
          capability: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          state: string;
          /** @sqlType BIGINT */
          n_facilities: number;
          /** @sqlType DOUBLE */
          trust_weighted: number;
          /** @sqlType DOUBLE */
          avg_trust: number;
          /** @sqlType BIGINT */
          geocoded: number;
          /** @sqlType BIGINT */
          n_with_capacity: number;
          /** @sqlType DOUBLE */
          total_reported_capacity: number;
          /** @sqlType INT */
          population: number;
          /** @sqlType DOUBLE */
          clean_fuel_pct: number;
          /** @sqlType DOUBLE */
          women_tobacco_pct: number;
          /** @sqlType DOUBLE */
          men_tobacco_pct: number;
          /** @sqlType DOUBLE */
          adult_tobacco_pct: number;
          /** @sqlType DOUBLE */
          child_ari_pct: number;
          /** @sqlType DOUBLE */
          insurance_pct: number;
          /** @sqlType DOUBLE */
          copd_risk_score: number;
          /** @sqlType DOUBLE */
          gap_score: number;
          /** @sqlType STRING */
          data_confidence: string;
        }>;
      };
  }
}
